"""Initial_schema

Revision ID: ea39fc5982bb
Revises: 
Create Date: 2026-01-30 12:34:01.533236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ea39fc5982bb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('derivation_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_derivation_index'), 'users', ['derivation_index'], unique=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('wallets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('chain', sa.String(), nullable=False),
    sa.Column('derivation_path', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wallets_address'), 'wallets', ['address'], unique=False)
    op.create_index(op.f('ix_wallets_chain'), 'wallets', ['chain'], unique=False)
    op.create_index(op.f('ix_wallets_id'), 'wallets', ['id'], unique=False)
    op.drop_index(op.f('TST_Lock_agreementId_idx'), table_name='TST_Lock')
    op.drop_index(op.f('TST_Lock_contractLockId_key'), table_name='TST_Lock')
    op.drop_index(op.f('TST_Lock_released_idx'), table_name='TST_Lock')
    op.drop_index(op.f('TST_Lock_userId_idx'), table_name='TST_Lock')
    op.drop_table('TST_Lock')
    op.execute('DROP TABLE IF EXISTS "Wallet" CASCADE')
    op.execute('DROP TABLE IF EXISTS "User" CASCADE')
    op.drop_index(op.f('StrategyDecision_createdAt_idx'), table_name='StrategyDecision')
    op.drop_index(op.f('StrategyDecision_strategyId_idx'), table_name='StrategyDecision')
    op.drop_table('StrategyDecision')
    op.drop_index(op.f('P2PAgreement_borrowerId_idx'), table_name='P2PAgreement')
    op.drop_index(op.f('P2PAgreement_lenderId_idx'), table_name='P2PAgreement')
    op.drop_index(op.f('P2PAgreement_status_idx'), table_name='P2PAgreement')
    op.drop_table('P2PAgreement')
    op.drop_index(op.f('PerformanceMetric_date_idx'), table_name='PerformanceMetric')
    op.drop_index(op.f('PerformanceMetric_date_key'), table_name='PerformanceMetric')
    op.drop_index(op.f('PerformanceMetric_userId_idx'), table_name='PerformanceMetric')
    op.drop_table('PerformanceMetric')
    op.drop_index(op.f('EntityAccessTier_entityType_idx'), table_name='EntityAccessTier')
    op.drop_index(op.f('EntityAccessTier_userId_entityType_key'), table_name='EntityAccessTier')
    op.drop_index(op.f('EntityAccessTier_userId_idx'), table_name='EntityAccessTier')
    op.drop_table('EntityAccessTier')
    op.drop_index(op.f('GuardianCheck_checkType_idx'), table_name='GuardianCheck')
    op.drop_index(op.f('GuardianCheck_status_idx'), table_name='GuardianCheck')
    op.drop_index(op.f('GuardianCheck_userId_idx'), table_name='GuardianCheck')
    op.drop_table('GuardianCheck')
    op.drop_index(op.f('APIKey_keyHash_idx'), table_name='APIKey')
    op.drop_index(op.f('APIKey_keyHash_key'), table_name='APIKey')
    op.drop_index(op.f('APIKey_userId_idx'), table_name='APIKey')
    op.drop_table('APIKey')
    op.drop_index(op.f('EntityLog_createdAt_idx'), table_name='EntityLog')
    op.drop_index(op.f('EntityLog_entityType_idx'), table_name='EntityLog')
    op.drop_table('EntityLog')
    op.drop_table('_prisma_migrations')
    op.drop_index(op.f('Transaction_createdAt_idx'), table_name='Transaction')
    op.drop_index(op.f('Transaction_status_idx'), table_name='Transaction')
    op.drop_index(op.f('Transaction_txHash_idx'), table_name='Transaction')
    op.drop_index(op.f('Transaction_txHash_key'), table_name='Transaction')
    op.execute('DROP TABLE IF EXISTS "Transaction" CASCADE')
    op.drop_index(op.f('Strategy_status_idx'), table_name='Strategy')
    op.drop_index(op.f('Strategy_userId_idx'), table_name='Strategy')
    op.drop_table('Strategy')
    op.drop_index(op.f('TST_Stake_active_idx'), table_name='TST_Stake')
    op.drop_index(op.f('TST_Stake_contractStakeId_key'), table_name='TST_Stake')
    op.drop_index(op.f('TST_Stake_tier_idx'), table_name='TST_Stake')
    op.drop_index(op.f('TST_Stake_userId_idx'), table_name='TST_Stake')
    op.drop_table('TST_Stake')
    op.drop_index(op.f('FeatureFlag_name_idx'), table_name='FeatureFlag')
    op.drop_index(op.f('FeatureFlag_name_key'), table_name='FeatureFlag')
    op.drop_table('FeatureFlag')
    op.drop_index(op.f('AuditTrail_action_idx'), table_name='AuditTrail')
    op.drop_index(op.f('AuditTrail_createdAt_idx'), table_name='AuditTrail')
    op.drop_index(op.f('AuditTrail_userId_idx'), table_name='AuditTrail')
    op.drop_table('AuditTrail')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('AuditTrail',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('userId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('action', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('resourceType', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('resourceId', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ipAddress', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('userAgent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('oldValue', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('newValue', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['User.id'], name=op.f('AuditTrail_userId_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('AuditTrail_pkey'))
    )
    op.create_index(op.f('AuditTrail_userId_idx'), 'AuditTrail', ['userId'], unique=False)
    op.create_index(op.f('AuditTrail_createdAt_idx'), 'AuditTrail', ['createdAt'], unique=False)
    op.create_index(op.f('AuditTrail_action_idx'), 'AuditTrail', ['action'], unique=False)
    op.create_table('FeatureFlag',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('isEnabled', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('rolloutPercentage', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('targetUsers', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('FeatureFlag_pkey'))
    )
    op.create_index(op.f('FeatureFlag_name_key'), 'FeatureFlag', ['name'], unique=True)
    op.create_index(op.f('FeatureFlag_name_idx'), 'FeatureFlag', ['name'], unique=False)
    op.create_table('TST_Stake',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('userId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('tier', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=28, scale=8), autoincrement=False, nullable=False),
    sa.Column('stakedAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False),
    sa.Column('expiresAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False),
    sa.Column('active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('unstakedAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=True),
    sa.Column('contractStakeId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('txHash', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['User.id'], name=op.f('TST_Stake_userId_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('TST_Stake_pkey'))
    )
    op.create_index(op.f('TST_Stake_userId_idx'), 'TST_Stake', ['userId'], unique=False)
    op.create_index(op.f('TST_Stake_tier_idx'), 'TST_Stake', ['tier'], unique=False)
    op.create_index(op.f('TST_Stake_contractStakeId_key'), 'TST_Stake', ['contractStakeId'], unique=True)
    op.create_index(op.f('TST_Stake_active_idx'), 'TST_Stake', ['active'], unique=False)
    op.create_table('Strategy',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('userId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('initialCapital', sa.NUMERIC(precision=28, scale=8), autoincrement=False, nullable=False),
    sa.Column('currentValue', sa.NUMERIC(precision=28, scale=8), autoincrement=False, nullable=False),
    sa.Column('targetAsset', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'paused'::text"), autoincrement=False, nullable=False),
    sa.Column('vetoStatus', sa.TEXT(), server_default=sa.text("'none'::text"), autoincrement=False, nullable=False),
    sa.Column('totalReturn', sa.NUMERIC(precision=28, scale=8), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('returnPercentage', sa.NUMERIC(precision=10, scale=4), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('winRate', sa.NUMERIC(precision=5, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('startedAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=True),
    sa.Column('endedAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=True),
    sa.Column('updatedAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['User.id'], name=op.f('Strategy_userId_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('Strategy_pkey'))
    )
    op.create_index(op.f('Strategy_userId_idx'), 'Strategy', ['userId'], unique=False)
    op.create_index(op.f('Strategy_status_idx'), 'Strategy', ['status'], unique=False)
    op.create_table('Transaction',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('walletId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('txHash', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'pending'::text"), autoincrement=False, nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=28, scale=8), autoincrement=False, nullable=False),
    sa.Column('assetType', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('chain', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('fromAddress', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('toAddress', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('gasUsed', sa.NUMERIC(precision=20, scale=8), autoincrement=False, nullable=True),
    sa.Column('gasPaid', sa.NUMERIC(precision=28, scale=8), autoincrement=False, nullable=True),
    sa.Column('blockNumber', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('blockTimestamp', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=True),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('confirmedAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['walletId'], ['Wallet.id'], name=op.f('Transaction_walletId_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('Transaction_pkey'))
    )
    op.create_index(op.f('Transaction_walletId_idx'), 'Transaction', ['walletId'], unique=False)
    op.create_index(op.f('Transaction_txHash_key'), 'Transaction', ['txHash'], unique=True)
    op.create_index(op.f('Transaction_txHash_idx'), 'Transaction', ['txHash'], unique=False)
    op.create_index(op.f('Transaction_status_idx'), 'Transaction', ['status'], unique=False)
    op.create_index(op.f('Transaction_createdAt_idx'), 'Transaction', ['createdAt'], unique=False)
    op.create_table('_prisma_migrations',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('checksum', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('finished_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('migration_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('logs', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('rolled_back_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('applied_steps_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('_prisma_migrations_pkey'))
    )
    op.create_table('EntityLog',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('entityType', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('cycle', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('startTime', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False),
    sa.Column('endTime', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False),
    sa.Column('duration', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('dataPointsProcessed', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('anomaliesDetected', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('decisionsGenerated', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('errorMessage', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('EntityLog_pkey'))
    )
    op.create_index(op.f('EntityLog_entityType_idx'), 'EntityLog', ['entityType'], unique=False)
    op.create_index(op.f('EntityLog_createdAt_idx'), 'EntityLog', ['createdAt'], unique=False)
    op.create_table('APIKey',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('userId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('keyPrefix', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('keyHash', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('tier', sa.TEXT(), server_default=sa.text("'free'::text"), autoincrement=False, nullable=False),
    sa.Column('requestsPerDay', sa.INTEGER(), server_default=sa.text('100'), autoincrement=False, nullable=False),
    sa.Column('requestsUsedToday', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('isActive', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('expiresAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=True),
    sa.Column('lastUsedAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['User.id'], name=op.f('APIKey_userId_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('APIKey_pkey'))
    )
    op.create_index(op.f('APIKey_userId_idx'), 'APIKey', ['userId'], unique=False)
    op.create_index(op.f('APIKey_keyHash_key'), 'APIKey', ['keyHash'], unique=True)
    op.create_index(op.f('APIKey_keyHash_idx'), 'APIKey', ['keyHash'], unique=False)
    op.create_table('GuardianCheck',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('checkType', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('severity', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('userId', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('strategyId', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('anomalyScore', sa.NUMERIC(precision=5, scale=4), autoincrement=False, nullable=False),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'pending'::text"), autoincrement=False, nullable=False),
    sa.Column('approverNotes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('approvedAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=True),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('resolvedAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('GuardianCheck_pkey'))
    )
    op.create_index(op.f('GuardianCheck_userId_idx'), 'GuardianCheck', ['userId'], unique=False)
    op.create_index(op.f('GuardianCheck_status_idx'), 'GuardianCheck', ['status'], unique=False)
    op.create_index(op.f('GuardianCheck_checkType_idx'), 'GuardianCheck', ['checkType'], unique=False)
    op.create_table('EntityAccessTier',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('userId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('entityType', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tstReserved', sa.NUMERIC(precision=28, scale=8), autoincrement=False, nullable=False),
    sa.Column('quotaPerDay', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quotaUsedToday', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('lastResetTime', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('contractResId', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['User.id'], name=op.f('EntityAccessTier_userId_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('EntityAccessTier_pkey'))
    )
    op.create_index(op.f('EntityAccessTier_userId_idx'), 'EntityAccessTier', ['userId'], unique=False)
    op.create_index(op.f('EntityAccessTier_userId_entityType_key'), 'EntityAccessTier', ['userId', 'entityType'], unique=True)
    op.create_index(op.f('EntityAccessTier_entityType_idx'), 'EntityAccessTier', ['entityType'], unique=False)
    op.create_table('PerformanceMetric',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('userId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('date', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False),
    sa.Column('totalValue', sa.NUMERIC(precision=28, scale=8), autoincrement=False, nullable=False),
    sa.Column('totalDeposits', sa.NUMERIC(precision=28, scale=8), autoincrement=False, nullable=False),
    sa.Column('totalWithdrawals', sa.NUMERIC(precision=28, scale=8), autoincrement=False, nullable=False),
    sa.Column('totalReturn', sa.NUMERIC(precision=28, scale=8), autoincrement=False, nullable=False),
    sa.Column('returnPercentage', sa.NUMERIC(precision=10, scale=4), autoincrement=False, nullable=False),
    sa.Column('volatility', sa.NUMERIC(precision=5, scale=4), autoincrement=False, nullable=False),
    sa.Column('sharpeRatio', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False),
    sa.Column('maxDrawdown', sa.NUMERIC(precision=5, scale=4), autoincrement=False, nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['User.id'], name=op.f('PerformanceMetric_userId_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('PerformanceMetric_pkey'))
    )
    op.create_index(op.f('PerformanceMetric_userId_idx'), 'PerformanceMetric', ['userId'], unique=False)
    op.create_index(op.f('PerformanceMetric_date_key'), 'PerformanceMetric', ['date'], unique=True)
    op.create_index(op.f('PerformanceMetric_date_idx'), 'PerformanceMetric', ['date'], unique=False)
    op.create_table('P2PAgreement',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('borrowerId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('lenderId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('principalAmount', sa.NUMERIC(precision=28, scale=8), autoincrement=False, nullable=False),
    sa.Column('interestRate', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False),
    sa.Column('duration', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('assetType', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'pending'::text"), autoincrement=False, nullable=False),
    sa.Column('approvalCount', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('lenderApproved', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('borrowerApproved', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('disbursedAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=True),
    sa.Column('repaidAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=True),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['borrowerId'], ['User.id'], name=op.f('P2PAgreement_borrowerId_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lenderId'], ['User.id'], name=op.f('P2PAgreement_lenderId_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('P2PAgreement_pkey'))
    )
    op.create_index(op.f('P2PAgreement_status_idx'), 'P2PAgreement', ['status'], unique=False)
    op.create_index(op.f('P2PAgreement_lenderId_idx'), 'P2PAgreement', ['lenderId'], unique=False)
    op.create_index(op.f('P2PAgreement_borrowerId_idx'), 'P2PAgreement', ['borrowerId'], unique=False)
    op.create_table('StrategyDecision',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('strategyId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('decision', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('confidence', sa.NUMERIC(precision=5, scale=4), autoincrement=False, nullable=False),
    sa.Column('reasoning', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('perceptionScore', sa.NUMERIC(precision=5, scale=4), autoincrement=False, nullable=False),
    sa.Column('memoryScore', sa.NUMERIC(precision=5, scale=4), autoincrement=False, nullable=False),
    sa.Column('riskScore', sa.NUMERIC(precision=5, scale=4), autoincrement=False, nullable=False),
    sa.Column('executed', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('executionPrice', sa.NUMERIC(precision=28, scale=8), autoincrement=False, nullable=True),
    sa.Column('executionTxHash', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('executedAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['strategyId'], ['Strategy.id'], name=op.f('StrategyDecision_strategyId_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('StrategyDecision_pkey'))
    )
    op.create_index(op.f('StrategyDecision_strategyId_idx'), 'StrategyDecision', ['strategyId'], unique=False)
    op.create_index(op.f('StrategyDecision_createdAt_idx'), 'StrategyDecision', ['createdAt'], unique=False)
    op.create_table('User',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('email', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('phone', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('phoneVerified', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('emailVerified', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('avatar', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('kycStatus', sa.TEXT(), server_default=sa.text("'pending'::text"), autoincrement=False, nullable=False),
    sa.Column('kycSubmittedAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=True),
    sa.Column('kycApprovedAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=True),
    sa.Column('riskProfile', sa.TEXT(), server_default=sa.text("'moderate'::text"), autoincrement=False, nullable=False),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'active'::text"), autoincrement=False, nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('User_pkey'))
    )
    op.create_index(op.f('User_kycStatus_idx'), 'User', ['kycStatus'], unique=False)
    op.create_index(op.f('User_email_key'), 'User', ['email'], unique=True)
    op.create_index(op.f('User_email_idx'), 'User', ['email'], unique=False)
    op.create_table('Wallet',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('userId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('address', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('chain', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('walletType', sa.TEXT(), server_default=sa.text("'user'::text"), autoincrement=False, nullable=False),
    sa.Column('derivationPath', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('balanceUSDT', sa.NUMERIC(precision=28, scale=8), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('balanceUSDC', sa.NUMERIC(precision=28, scale=8), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('balanceNative', sa.NUMERIC(precision=28, scale=8), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('balanceTST', sa.NUMERIC(precision=28, scale=8), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('isActive', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['User.id'], name=op.f('Wallet_userId_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('Wallet_pkey'))
    )
    op.create_index(op.f('Wallet_userId_idx'), 'Wallet', ['userId'], unique=False)
    op.create_index(op.f('Wallet_userId_chain_key'), 'Wallet', ['userId', 'chain'], unique=True)
    op.create_index(op.f('Wallet_address_key'), 'Wallet', ['address'], unique=True)
    op.create_index(op.f('Wallet_address_idx'), 'Wallet', ['address'], unique=False)
    op.create_table('TST_Lock',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('userId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('agreementId', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('amount', sa.NUMERIC(precision=28, scale=8), autoincrement=False, nullable=False),
    sa.Column('lockedUntil', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False),
    sa.Column('released', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('releasedAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=True),
    sa.Column('contractLockId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('txHash', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['agreementId'], ['P2PAgreement.id'], name=op.f('TST_Lock_agreementId_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['userId'], ['User.id'], name=op.f('TST_Lock_userId_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('TST_Lock_pkey'))
    )
    op.create_index(op.f('TST_Lock_userId_idx'), 'TST_Lock', ['userId'], unique=False)
    op.create_index(op.f('TST_Lock_released_idx'), 'TST_Lock', ['released'], unique=False)
    op.create_index(op.f('TST_Lock_contractLockId_key'), 'TST_Lock', ['contractLockId'], unique=True)
    op.create_index(op.f('TST_Lock_agreementId_idx'), 'TST_Lock', ['agreementId'], unique=False)
    op.drop_index(op.f('ix_wallets_id'), table_name='wallets')
    op.drop_index(op.f('ix_wallets_chain'), table_name='wallets')
    op.drop_index(op.f('ix_wallets_address'), table_name='wallets')
    op.drop_table('wallets')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_derivation_index'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
