"""fix_missing_user_id

Revision ID: f302a3a585e6
Revises: f8a9b2c3d4e5
Create Date: 2026-01-31 04:42:11.752799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f302a3a585e6'
down_revision: Union[str, Sequence[str], None] = 'f8a9b2c3d4e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hearing_records', sa.Column('user_id', sa.UUID(), nullable=False))
    op.add_column('hearing_records', sa.Column('intent', sa.String(), nullable=False))
    op.add_column('hearing_records', sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('hearing_records', sa.Column('transcript', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('hearing_records', sa.Column('final_verdict', sa.String(), nullable=False))
    op.add_column('hearing_records', sa.Column('final_reason', sa.String(), nullable=True))
    op.drop_index(op.f('ix_hearing_records_created_at'), table_name='hearing_records')
    op.drop_index(op.f('ix_hearing_records_regime_label'), table_name='hearing_records')
    op.drop_index(op.f('ix_hearing_records_risk_allowed'), table_name='hearing_records')
    op.drop_index(op.f('ix_hearing_records_session_id'), table_name='hearing_records')
    op.drop_index(op.f('ix_hearing_records_subject'), table_name='hearing_records')
    op.create_index(op.f('ix_hearing_records_final_verdict'), 'hearing_records', ['final_verdict'], unique=False)
    op.create_index(op.f('ix_hearing_records_user_id'), 'hearing_records', ['user_id'], unique=False)
    op.drop_column('hearing_records', 'risk_allowed')
    op.drop_column('hearing_records', 'data')
    op.drop_column('hearing_records', 'confidence_band')
    op.drop_column('hearing_records', 'subject')
    op.drop_column('hearing_records', 'veto_count')
    op.drop_column('hearing_records', 'session_id')
    op.drop_column('hearing_records', 'created_at')
    op.drop_column('hearing_records', 'regime_label')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hearing_records', sa.Column('regime_label', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('hearing_records', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('hearing_records', sa.Column('session_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('hearing_records', sa.Column('veto_count', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('hearing_records', sa.Column('subject', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('hearing_records', sa.Column('confidence_band', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('hearing_records', sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('hearing_records', sa.Column('risk_allowed', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_hearing_records_user_id'), table_name='hearing_records')
    op.drop_index(op.f('ix_hearing_records_final_verdict'), table_name='hearing_records')
    op.create_index(op.f('ix_hearing_records_subject'), 'hearing_records', ['subject'], unique=False)
    op.create_index(op.f('ix_hearing_records_session_id'), 'hearing_records', ['session_id'], unique=False)
    op.create_index(op.f('ix_hearing_records_risk_allowed'), 'hearing_records', ['risk_allowed'], unique=False)
    op.create_index(op.f('ix_hearing_records_regime_label'), 'hearing_records', ['regime_label'], unique=False)
    op.create_index(op.f('ix_hearing_records_created_at'), 'hearing_records', ['created_at'], unique=False)
    op.drop_column('hearing_records', 'final_reason')
    op.drop_column('hearing_records', 'final_verdict')
    op.drop_column('hearing_records', 'transcript')
    op.drop_column('hearing_records', 'started_at')
    op.drop_column('hearing_records', 'intent')
    op.drop_column('hearing_records', 'user_id')
    # ### end Alembic commands ###
